# Generated by Django 3.2.5 on 2021-11-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfigClientEnabled',
            fields=[
                ('site_uuid', models.UUIDField(primary_key=True, serialize=False,
                                               verbose_name='UUID of the site the client enabled for.')),
            ],
        ),
    ]
