# Generated by Django 2.2.24 on 2022-01-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfigclientenabled',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False,
                                   verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteconfigclientenabled',
            name='site_uuid',
            field=models.UUIDField(unique=True, verbose_name='UUID of the site the client enabled for.'),
        ),
    ]
