# Generated by Django 2.2.24 on 2022-01-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config_client', '0002_use_numeric_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfigclientenabled',
            name='note',
            field=models.CharField(default='', max_length=255, verbose_name='Note for the the admin.'),
            preserve_default=False,
        ),
    ]
